SyntaxError: Pre-generate message in constructor
We don't need to store reference to input stream, which caused crash
when printing exceptions thrown in `run` script.